### ISSUE TITLE
Useable on pop! OS and webcam or iPhone X?

### ISSUE THREAD

**Issue by mac20211991** [Iron-Stag-Games/Godot-NI-mate-Motion-Capture#11]
Hello nice plug-in thanks for dev an deliver :)

I wanted to ask if it's possible to stream video from my webcam or iPhone X into godot and capture skelet or facial motion with NImate? 
My above mentioned OS is not very famous but it should work with the ubuntu version. 
Thank you so much :)

**Comment by hoontee** [comment]
NI mate isn't available on iOS. You will need to record tracking data on a compatible system:

https://github.com/hoontee/godot-ni-mate-motion-capture#delicode-ni-mate-downloads
