### ISSUE TITLE
Asus Xtion support / Add demo project

### ISSUE THREAD

**Issue by kallistisoft** [Iron-Stag-Games/Godot-NI-mate-Motion-Capture#7]
I'm running into problems trying to get the plugin to work....

Test Setup:
  Asus Xtion Sensor
  Delicode v2.14
  Godot v3.2.3 (Arch_Linux)

I've got Delicode running on my windows machine sending the OSC data to my linux rig. I've tested the setup with the Blender plugin on linux and tracking works as expected, but the tracking window for the Ni-Mate plugin in godot is mangled -- looks like the root node is stuck?? Here is a video of the Delicode OpenNI 2 sample animation file being played https://streamable.com/ibl53q

Any help would be appreciated!
Also, by any chance might you release a simple demo project to accompany the plugin? I think it would be a big help with testing and helping people familiarize themselves with the plugin.

Thank You!

**Comment by hoontee** [comment]
The video you've provided is unrelated. Please update the issue.

As for a demo project, I will be adding one in the next few days as per your suggestion. You can expect files for both Godot and Blender.

**Comment by kallistisoft** [comment]
Thank you for your prompt reply. I updated the original post with the correct video link.

**Comment by hoontee** [comment]
Does your joint mapping look like this?

![image](https://user-images.githubusercontent.com/5272529/107135805-6f4a8c00-68c3-11eb-8e3b-3bdcd597ab0a.png)

**Comment by kallistisoft** [comment]
That looks like the problem... the tracking points for Kinect are different from the ones for OpenNI 2 (Asus Xtion)

Here's a screenshot of the mappings options: 
![screenshot](https://i.imgur.com/RKXMxSO.png)

**Comment by hoontee** [comment]
I will let you know when this sensor is supported. It shouldn't take long.

(Hopefully there aren't other joint layouts...)

**Comment by hoontee** [comment]
kallistisoft,

[Here is an experimental version of the addon.](https://github.com/hoontee/godot-ni-mate-motion-capture/files/5946240/ni_mate_motion_capture.zip) Please disable `Rotate Hands With Thumbs` and enable `Simple` and post a recording of what your rig looks like afterwards. Hopefully it's fixed!

![image](https://user-images.githubusercontent.com/5272529/107270185-4388ec80-6a10-11eb-9a4d-42edfa694493.png)

**Comment by kallistisoft** [comment]
Here's a recording of the rig with experimental version of the add-on, using the NI2 demo animation: https://streamable.com/sp3546

As you can see my results look a little different from yours-- shorter torso, and on upper arms and legs
Also there is a off-by-one bug selecting the Clamp options; clicking on X selects Y, and clicking Y selects Z

Thank you so much for your efforts!

**Comment by hoontee** [comment]
The torso will naturally be shorter due to different tracking points.

The hand/foot issues might have been fixed. Replace this file and tell me what happens:
[ni_mate_plugin.gd](https://github.com/hoontee/godot-ni-mate-motion-capture/files/5946919/ni_mate_plugin.zip)

**Comment by kallistisoft** [comment]
Great work! 

Feet, hands, and checkboxes work perfectly! 

Now I just need to figure out how to properly export my armature from Blender... The tracking is correct but the axis are all off, pretty sure that problem is on my side though :)

Thank you again!

**Comment by hoontee** [comment]
Here are a few resources to assist you while I try to make a demo project:

https://github.com/hoontee/godot-ni-mate-motion-capture/blob/master/README.md
https://github.com/godotengine/godot-blender-exporter
